# cspell:ignore gitui kubectx
# See: https://mise.jdx.dev/configuration.html for config options.
[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv

[tools]
####### Pinned versions
kubectl = "1.31"

######### Latest versions
bat = "latest"
fzf = "latest"
golang = 'latest'
golangci-lint = 'latest'
goreleaser = 'latest'
gh = "latest"
gitui = "latest"
helm = "latest"
k9s = "latest"
kubectx = "latest"
lsd = "latest"
starship = "latest"
yq = "latest"


[settings]
experimental = true
#http_timeout = "90s"
#jobs = 1
#yes = true
trusted_config_paths = ['/workspaces/']