# See: https://mise.jdx.dev/configuration.html for config options.
# NOTE: Top level tools are installed in home/vscode/config/mise/config.toml during setup.
#[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv
#EXAMPLE = 'bar'

# specify single or multiple versions of specific tools you want installed for this project.
# Below are examples.
# [tools]
# golang = '1.23.1'
# golangci-lint = '1.61.0'
# goreleaser = "2.3.2"
