name: Periodic Build and Release

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly
  workflow_dispatch: # Allows manual triggering

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ncipollo/release-action@v1
        with:
          body: "A test of the auto releaseer for v 1.0.1-beta.1"
          makeLatest: false
          prerelease: true
          tag: "v1.0.1-beta.1"
