name: Periodic Build and Release

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        # See: https://github.com/huggingface/semver-release-action?tab=readme-ov-file
        # and https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
      - name: Release
        uses: huggingface/semver-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}