# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - 'home/**'
      - 'scripts/**'
      - 'usr/**'
      - 'workflow_scripts/**'
      - '.dockerignore'
      - '.mise.toml'
      - '.pre-commit-config.yaml'
      - 'Dockerfile'

  schedule:
    - cron: '19 14 * * 5'
  workflow_dispatch: # Allows manual triggering

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Trivy Scan
    permissions:
      contents: write # for actions/checkout to fetch code and for SBOM to push results
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Log Into Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Docker Image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Upload Trivy Results
        uses: github/codeql-action/upload-sarif@fc7e4a0fa01c3cca5fd6a1fddec5c0740c977aa2
        with:
          sarif_file: 'trivy-results.sarif'

